### ISSUE TITLE
Implement and test the Plavec radius approximation

### ISSUE THREAD

**Issue by willclarkson** [thomassutter314/echoxrb#3]
As per Rob: the Plavec approximation is better than the Eggleton approximation (it's also in Frank, King & Raine). Should be implemented and at least one MCMC test run with the Plavec radius formula.

**Comment by willclarkson** [comment]
Thomas has done this - closing this for now

**Comment by thomassutter314** [comment]
Plavec approximation is not preferable to the Roche approximation. At phase ~.5, the 3D model gives results between Plavec and Roche
![3ModelsComparison](https://user-images.githubusercontent.com/54648552/75376411-da52ac80-5884-11ea-975c-3d2d82ba500a.png)
